return {
    require("plugins.telescope"),
    require("plugins.rose-pine"),
    require("plugins.treesitter"),
    require("plugins.harpoon"),
    require("plugins.undotree"),
    require("plugins.fugitive"),
    require("plugins.lualine"),
    require("plugins.bufferline"),
    require("plugins.catppuccin"),
    require("plugins.tokyonight"),
    require("plugins.coc"),
    require("plugins.conform"),
    require("plugins.noice"),
  }